# Generated by Django 5.2.9 on 2026-01-02 11:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية/الإقامة يجب أن يكون أرقام فقط (10 إلى 20 رقم).', regex='^\\d{10,20}$')], verbose_name='الهوية الوطنية / الإقامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف فرد',
                'verbose_name_plural': 'ملفات الأفراد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_number'], name='individuals_id_numb_3b14a6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('id_number', ''), _negated=True), name='individual_id_number_not_blank')],
            },
        ),
    ]
