# Generated by Django 6.0 on 2025-12-27 12:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='individualprofile',
            new_name='individuals_id_numb_3b14a6_idx',
            old_name='individuals_id_number_idx',
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='id_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية/الإقامة يجب أن يكون أرقام فقط (10 إلى 20 رقم).', regex='^\\d{10,20}$')], verbose_name='الهوية الوطنية / الإقامة'),
        ),
        migrations.AddConstraint(
            model_name='individualprofile',
            constraint=models.CheckConstraint(condition=models.Q(('id_number', ''), _negated=True), name='individual_id_number_not_blank'),
        ),
    ]
