# Generated by Django 6.0 on 2025-12-27 12:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationprofile',
            new_name='organizatio_categor_c6502c_idx',
            old_name='org_category_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationprofile',
            new_name='organizatio_org_nam_6123cb_idx',
            old_name='org_name_idx',
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='org_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم الجهة'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='representative_phone',
            field=models.CharField(help_text='10 أرقام فقط بدون +966', max_length=10, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يكون 10 أرقام فقط.', regex='^\\d{10}$')], verbose_name='رقم جوال ممثل الجهة'),
        ),
        migrations.AddConstraint(
            model_name='organizationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('map_url__gt', ''), ('location_description__gt', ''), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='org_location_at_least_one'),
        ),
    ]
