# Generated by Django 6.0 on 2025-12-26 13:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=120, verbose_name='اسم الجهة')),
                ('org_rep', models.CharField(max_length=80, verbose_name='ممثل الجهة')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='رقم التواصل يجب أن يكون 10 أرقام ويبدأ بـ 05.', regex='^05\\d{8}$')], verbose_name='رقم التواصل')),
                ('email', models.EmailField(max_length=120, verbose_name='البريد الإلكتروني')),
                ('message', models.TextField(max_length=1200, verbose_name='نص الرسالة')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الإرسال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent')),
                ('email_sent', models.BooleanField(default=False, verbose_name='تم إرسال البريد')),
                ('email_error', models.TextField(blank=True, default='', verbose_name='خطأ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
