# Generated by Django 6.0 on 2025-12-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_error',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='org_rep',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال بالبريد'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='org_representative',
            field=models.CharField(default='', max_length=200, verbose_name='ممثل الجهة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='send_error',
            field=models.TextField(blank=True, default='', verbose_name='خطأ الإرسال (إن وجد)'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='نص الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='org_name',
            field=models.CharField(max_length=200, verbose_name='اسم الجهة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='رقم التواصل'),
        ),
    ]
