# Generated by Django 6.0 on 2025-12-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='org_representative',
            field=models.CharField(blank=True, default='ممثل الجهة', max_length=120),
        ),
    ]
