# Generated by Django 6.0 on 2025-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_contactmessage_org_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_inbox_email', models.EmailField(default='support@thqaf.com', max_length=254, verbose_name='إيميل استقبال رسائل تواصل معنا')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال؟'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='org_name',
            field=models.CharField(max_length=255, verbose_name='اسم الجهة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='org_representative',
            field=models.CharField(max_length=255, verbose_name='ممثل الجهة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='send_error',
            field=models.TextField(blank=True, default='', verbose_name='خطأ الإرسال'),
        ),
    ]
