# Generated by Django 5.2.9 on 2026-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesetting_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة تواصل', 'verbose_name_plural': 'رسائل التواصل'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'إعدادات الموقع', 'verbose_name_plural': 'بريد وصول رسائل التواصل'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='org_representative',
            field=models.CharField(default='', max_length=255, verbose_name='ممثل الجهة'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
