# Generated by Django 6.0 on 2025-12-26 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'رمز تحقق بريد', 'verbose_name_plural': 'رموز تحقق البريد'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(max_length=6, verbose_name='رمز التحقق'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(verbose_name='ينتهي في'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدامه؟'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ORG', 'جهة'), ('IND', 'فرد'), ('TRAINER', 'مدرب'), ('STAFF', 'موظف')], db_index=True, default='IND', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
