# Generated by ChatGPT on 2025-12-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailotp_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SYSTEM_ADMIN", "مدير النظام"),
                    ("DEPT_MANAGER", "مدير الإدارة"),
                    ("SUPERVISOR", "مشرف"),
                    ("COURSE_COORDINATOR", "منسق الدورات"),
                    ("TRAINER", "مدرب"),
                    ("ORG", "جهة"),
                    ("IND", "فرد"),
                ],
                db_index=True,
                default="IND",
                help_text=(
                    "يحدد صلاحيات المستخدم داخل النظام. "
                    "تنبيه: أدوار (مدرب/مدير إدارة/مشرف/منسق دورات) يتم إنشاؤها من مدير النظام فقط."
                ),
                max_length=30,
                verbose_name="الدور",
            ),
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
                "permissions": [
                    ("manage_users", "إدارة المستخدمين بالكامل"),
                    ("view_all_data", "مشاهدة جميع البيانات في النظام"),
                    ("manage_courses", "إدارة الدورات"),
                    ("approve_courses", "اعتماد الدورات"),
                ],
            },
        ),
    ]
